
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 963863
	#The name of the modpack
	modpackName = "MyJonCraft SGS"
	#The version of the modpack
	modpackVersion = "v7.0.2 Release"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

