#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 05 12:36:11 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=BSL_v8.4.zip
enableShaders=false
